### ISSUE TITLE
Connecting to Dedicated Server Fails on Registry sync.

### ISSUE THREAD

**Issue by i509VCB** [fabric-community/spooky-time#130]
How to reproduce: Connect to a server with SpookyTime installed.

Error returned when connecting to Dedicated Server:
```
[18:37:46] [main/ERROR]: Registry remapping failed!
net.fabricmc.fabric.impl.registry.RemapException: Received ID map for minecraft:chunk_generator_type contains IDs unknown to the receiver!
 - spookytime:spooky
	at net.minecraft.util.registry.SimpleRegistry.remap(SimpleRegistry.java:675) ~[minecraft-1.14.4-mapped-net.fabricmc.yarn-13.jar:?]
	at net.fabricmc.fabric.impl.registry.RegistrySyncManager.apply(RegistrySyncManager.java:193) ~[net.fabricmc.yarn.1_14_4.13.net.fabricmc.fabric-api.fabric-registry-sync-v0-0.2.2+591e97ae42.jar:?]
	at net.fabricmc.fabric.impl.registry.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:79) ~[net.fabricmc.yarn.1_14_4.13.net.fabricmc.fabric-api.fabric-registry-sync-v0-0.2.2+591e97ae42.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_161]
	at net.minecraft.util.ThreadExecutor.runSafely(ThreadExecutor.java:144) [minecraft-1.14.4-mapped-net.fabricmc.yarn-13.jar:?]
	at net.minecraft.util.NonBlockingThreadExecutor.runSafely(NonBlockingThreadExecutor.java:23) [minecraft-1.14.4-mapped-net.fabricmc.yarn-13.jar:?]
	at net.minecraft.util.ThreadExecutor.executeQueuedTask(ThreadExecutor.java:118) [minecraft-1.14.4-mapped-net.fabricmc.yarn-13.jar:?]
	at net.minecraft.util.ThreadExecutor.executeTaskQueue(ThreadExecutor.java:103) [minecraft-1.14.4-mapped-net.fabricmc.yarn-13.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:915) [minecraft-1.14.4-mapped-net.fabricmc.yarn-13.jar:?]
	at net.minecraft.client.MinecraftClient.start(MinecraftClient.java:410) [minecraft-1.14.4-mapped-net.fabricmc.yarn-13.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) [minecraft-1.14.4-mapped-net.fabricmc.yarn-13.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178) [net.fabricmc.yarn.1_14_4.13.net.fabricmc.fabric-loader-0.6.2+build.166.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131) [net.fabricmc.yarn.1_14_4.13.net.fabricmc.fabric-loader-0.6.2+build.166.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [net.fabricmc.yarn.1_14_4.13.net.fabricmc.fabric-loader-0.6.2+build.166.jar:?]
```

**Comment by i509VCB** [comment]
Fixed by https://github.com/fabric-community/spooky-time/pull/144
