### ISSUE TITLE
Not compatible with OptiFine

### ISSUE THREAD

**Issue by SimoneComitini** [fabric-community/spooky-time#174]
When OptiFine is present, it crashes upon launch

MultiMC version: 0.6.7-1375

Minecraft folder is:
C:/Users/utente/Desktop/MultiMC/instances/0.6.3/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_221/bin/javaw.exe

Usando Java 1.8.0_221 su un'architettura a 64-bit.

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  C:/Users/utente/Desktop/MultiMC/instances/0.6.3/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/utente/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/utente/Desktop/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/utente/Desktop/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/utente/Desktop/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/utente/Desktop/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/utente/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/utente/Desktop/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/utente/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/utente/Desktop/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/utente/Desktop/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/utente/Desktop/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/utente/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/utente/Desktop/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/utente/Desktop/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/utente/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/utente/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/utente/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/utente/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/utente/Desktop/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/utente/Desktop/MultiMC/libraries/net/fabricmc/fabric-loader/0.6.3+build.167/fabric-loader-0.6.3+build.167.jar
  C:/Users/utente/Desktop/MultiMC/libraries/net/fabricmc/yarn/1.14.4+build.14/yarn-1.14.4+build.14.jar
  C:/Users/utente/Desktop/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.1.1.8/tiny-mappings-parser-0.1.1.8.jar
  C:/Users/utente/Desktop/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.38/sponge-mixin-0.7.11.38.jar
  C:/Users/utente/Desktop/MultiMC/libraries/net/fabricmc/tiny-remapper/0.1.0.40/tiny-remapper-0.1.0.40.jar
  C:/Users/utente/Desktop/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  C:/Users/utente/Desktop/MultiMC/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/ow2/asm/asm/7.1/asm-7.1.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/ow2/asm/asm-analysis/7.1/asm-analysis-7.1.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/ow2/asm/asm-commons/7.1/asm-commons-7.1.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/ow2/asm/asm-tree/7.1/asm-tree-7.1.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/ow2/asm/asm-util/7.1/asm-util-7.1.jar
  C:/Users/utente/Desktop/MultiMC/libraries/com/mojang/minecraft/1.14.4/minecraft-1.14.4-client.jar

Native libraries:
  C:/Users/utente/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/utente/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/utente/Desktop/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] 1.14.4-trinkets-1.1.5
  [✔️] fabric-api-0.4.1+build.245-1.14
  [✔️] fabric-language-kotlin-1.3.50+build.1
  [✔️] optifabric-0.5.2
  [✔️] OptiFine_1.14.4_HD_U_F4
  [✔️] RoughlyEnoughItems-3.1.5+build.31
  [✔️] TheHallow-1.0.0-beta+1.14.4

Params:
  --username  --version MultiMC5 --gameDir C:/Users/utente/Desktop/MultiMC/instances/0.6.3/.minecraft --assetsDir C:/Users/utente/Desktop/MultiMC/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms3072m, -Xmx6144m, -Duser.language=en]

Id del Processo di Minecraft: 16664

Using onesix launcher.

[14:37:44] [main/INFO]: Loading for game Minecraft 1.14.4
[14:37:47] [main/WARN]: Mod `worldtraveler` (1.0.4) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[14:37:47] [main/WARN]: Mod `mm` (1.6) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[14:37:47] [main/WARN]: Mod `cloth` (0.6.0) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[14:37:47] [main/INFO]: [FabricLoader] Loading 55 mods: fabric-renderer-api-v1@0.1.1+591e97ae42, fabric-keybindings-v0@0.1.1+591e97ae42, trinkets@1.1.5, fabricloader@0.6.3+build.167, org_jetbrains_kotlinx_kotlinx-coroutines-core@1.3.0, org_zeroturnaround_zt-zip@1.13, fabric-containers-v0@0.1.2+591e97ae42, fabric-dimensions-v1@0.1.0+369ab22e42, net_fabricmc_stitch@0.2.1.61, worldtraveler@1.0.4, fabric-api-base@0.1.1+2ac73e7242, mm@1.6, fabric-rendering-data-attachment-v1@0.1.1+c877038942, fabric-textures-v0@0.1.4+591e97ae42, fabric-rendering-fluids-v1@0.1.2+36f27aa342, org_jetbrains_kotlin_kotlin-stdlib@1.3.50, fabric-loot-tables-v1@0.1.0+591e97ae42, fabric@0.4.1+build.245-1.14, org_slf4j_slf4j-api@1.7.26, fabric-particles-v1@0.1.1+c877038942, fabric-networking-v0@0.1.3+591e97ae42, cloth@0.6.0, minecraft@1.14.4, fabric-networking-blockentity-v0@0.2.0+c877038942, thehallow@1.0.0-beta+1.14.4, jankson@1.0.0+j1.1.2, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.3.50, fabric-renderer-indigo@0.1.13+591e97ae42, fiber2cloth@1.2.0, fabric-biomes-v1@0.1.0+591e97ae42, fabric-crash-report-info-v1@0.1.1+591e97ae42, org_slf4j_slf4j-simple@1.7.26, fabric-events-interaction-v0@0.1.1+591e97ae42, roughlyenoughitems@3.1.5+build.31, fabric-language-kotlin@1.3.50+build.1, fabric-rendering-v0@0.1.1+591e97ae42, cloth-config2@1.1.2, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.3.0, fabric-resource-loader-v0@0.1.3+591e97ae42, me_zeroeightsix_fiber@0.6.0-7, org_jetbrains_kotlin_kotlin-reflect@1.3.50, fabric-content-registries-v0@0.1.1+591e97ae42, fabric-tag-extensions-v0@0.1.1+591e97ae42, optifabric@0.5.2, tinyconfig@1.1.2, cardinal-components-entity@2.0.3, fabric-commands-v0@0.1.1+591e97ae42, fabric-registry-sync-v0@0.2.2+591e97ae42, cardinal-components-base@2.0.3, fabric-mining-levels-v0@0.1.0+591e97ae42, fabric-events-lifecycle-v0@0.1.1+591e97ae42, fabric-models-v0@0.1.0+591e97ae42, fabric-item-groups-v0@0.1.0+591e97ae42, fabric-object-builders-v0@0.1.1+591e97ae42, org_jetbrains_annotations@17.0.0
[14:37:47] [main/WARN]: Mod `net_fabricmc_stitch` (0.2.1.61) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[14:37:47] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/utente/Desktop/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.38/sponge-mixin-0.7.11.38.jar Service=Knot/Fabric Env=CLIENT
[14:37:48] [main/INFO]: Compatibility level set to JAVA_8
[14:37:48] [main/WARN]: Reference map 'build-refmap.json' for worldtraveler.mixins.json could not be read. If this is a development environment you can ignore this message
Found existing patched optifine jar, using that
[14:37:50] [main/INFO]: [OptiFine] *** Reflector Forge ***
[14:37:50] [main/INFO]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method localvar$applyFog$zhf000(F)F in thehallow.mixins.json:client.BackgroundRendererMixin failed injection check, (0/1) succeeded. Using refmap thehallow-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1203)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:939)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:323)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:281)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:197)
	at net.minecraft.class_3268.<clinit>(class_3268.java:82)
	at net.minecraft.class_1066.<init>(class_1066.java:61)
	at net.minecraft.class_310.<init>(class_310.java:351)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:180)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:197)
	at net.minecraft.class_3268.<clinit>(class_3268.java:82)
	at net.minecraft.class_1066.<init>(class_1066.java:61)
	at net.minecraft.class_310.<init>(class_310.java:351)
	at net.minecraft.client.main.Main.main(Main.java:155)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method localvar$applyFog$zhf000(F)F in thehallow.mixins.json:client.BackgroundRendererMixin failed injection check, (0/1) succeeded. Using refmap thehallow-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1203)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:939)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:323)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:281)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 23 more
Exiting with -1
Il processo si è chiuso con codice -1.

**Comment by Shnupbups** [comment]
This is a known issue which we unfortunately can't fix easily. Optifine does some very invasive changes to rendering of... well, everything.

**Comment by SimoneComitini** [comment]
I see...so there's no fix for this...If that's so, how was that screenshot with shaders taken?

**Comment by Shnupbups** [comment]
I'm... honestly not sure. Draylar took the screenshots, I do remember him saying that he crashed with Optifine when actually entering The Hallow dimension, so I'm not sure why you can't load the game with Optifine at all...

**Comment by SimoneComitini** [comment]
Oh okay , thanks a lot for your help!

**Comment by i509VCB** [comment]
I know the hallow does something to apply fog effect, however optifine seems to entirely overwrite that change, hence mixin failing. Unless someone decides to overhaul the system to work under the constraints of Indigo, vanilla and optifine.

Until someone PRs a fix I would go wontfix since optifabric isn't natively supported and maybe as far as adding it to breaks till we fix conflicts.

**Comment by LemmaEOF** [comment]
The easiest thing to do would be to use a mixin plugin to disable our fog stuff if optifine is loaded.

**Comment by Shnupbups** [comment]
Fixed by #175

**Comment by LemmaEOF** [comment]
#175 has been merged, so a fixed build will be out soon!
